language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: bash ./test.sh
env:
  global:
  - TESTMODULE: spaceshooter.py
  - GH_REPO: github.com/Runpython-IntroProgramming/tests.git
